### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by sicaboy**

### CODE REVIEW

**Comment by Venorcis** [comment]
Is there an ETA on this? Looks like a very straightforward update 😁

**Comment by edamov** [comment]
@Venorcis Some checks were not successful on Scrutinizer. Need someone to check it.
As soon as it will be successful I merge the PR

**Comment by Venorcis** [comment]
> @Venorcis Some checks were not successful on Scrutinizer. Need someone to check it.
> As soon as it will be successful I merge the PR

It's failing on "PHP Analyzer: Determining Dependencies", not sure why, I don't see any error output?

**Comment by edamov** [comment]
I also don't see any errors. Maybe we need try to install locally composer dependencies for this PR on PHP version 8

**Comment by Venorcis** [comment]
> I also don't see any errors. Maybe we need try to install locally composer dependencies for this PR on PHP version 8

I've just tried this using `PHP 8.0.0 (cli) (built: Jan  4 2021 00:49:34) ( NTS )`; it works fine! 59 packages installed succesfully.

**Comment by edamov** [comment]
@Venorcis Thanks! I merged and created new version 0.12.0

**Pull request merged**
