### PR TITLE
Upgrade to webtokens2-library

### PR DESCRIPTION
**Pull request by rasmusbe**
I took the opportunity to create a PR of the work done by @CatoTH to support web-token 2.0.
I'm unable to fix the conflict in composer.json since I don't have write access but I hope this will be solved easily 

Solves issue #74

### CODE REVIEW

**Comment by CatoTH** [comment]
@rasmusbe I just removed the conflicting line.

**Comment by rasmusbe** [comment]
Travis fails on php7.1 not being supported, that should be fine now when it's deprecated. 
Probably should update travis-config and readme if this gets merged.

**Comment by edamov** [comment]
Also, we have the end of active support php7.2 very soon :smiley: 
I think about splitting the current version of the library and a new branch with a stable release (v.1.0.0, maybe alpha at first) with the minimum required php version 7.2 (or 7.3?).

**Comment by edamov** [comment]
I think we can merge this PR with php7.2 before a stable release will be created.
But we need update travis config and readme.
@rasmusbe Could you update your PR please?

**Comment by rasmusbe** [comment]
> Also, we have the end of active support php7.2 very soon 😃
> I think about splitting the current version of the library and a new branch with a stable release (v.1.0.0, maybe alpha at first) with the minimum required php version 7.2 (or 7.3?).

Sounds good! Since everything seems to work in 7.2 I think you can keep minimum version at that until anything breaks.

> I think we can merge this PR with php7.2 before a stable release will be created.
> But we need update travis config and readme.
> @rasmusbe Could you update your PR please?

I just created the PR from @CatoTH repo to get things going, and i didn't want to take any credits for his works. But I can create another PR only containing the changes needed for php7.2.

**Pull request closed without merging**
