### PR TITLE
 migrated to web-token/jwt-framework

### PR DESCRIPTION
**Pull request by aporat**

### CODE REVIEW

**Comment by Spomky** [comment]
Hi,

This PR looks good to me, however I have a minor comment: you should not install the whole framework but only the components you need.

Instead of `"web-token/jwt-framework": "^1.3"`, you should require:

* `"web-token/web-token/jwt-signature-algorithm-ecdsa": "^1.3"`: provides `ES512` signature algorithm support and depends on the core and signature components,
* `"web-token/web-token/jwt-key-mgmt": "^1.3"`: provides the `JWKFactory` class.

Please note that the class `Jose\Component\Core\Converter\StandardConverter` will be deprecated in v1 and removed in v2. You can still use it as you do in this PR and remove it when migrating from v1 to v2.

**Comment by koenhoeijmakers** [comment]
I'd like to add that Travis-CI is failing due to `git` not being available on the docker image, so don't worry about that for now.

**Comment by aporat** [comment]
@Spomky thanks again for making this package. I changed the composer requirements. 

Regarding the deprecated notice, even that `StandardConverter` is deprecated, looks like this class has to be used in the current released version. looks like the new `Jose\Component\Core\Util\JsonConverter` class is not yet compatible with the `JWSBuilder` constructor.

**Comment by edamov** [comment]
@aporat Thanks for your PR! Now it's merged.

**Pull request merged**
